//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.07 at 10:32:12 PM PDT 
//


package xmlobjects;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xmlobjects package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Inputs_QNAME = new QName("http://24.19.117.165/xml/input", "inputs");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xmlobjects
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InputSet }
     * 
     */
    public InputSet createInputSet() {
        return new InputSet();
    }

    /**
     * Create an instance of {@link FlowInput }
     * 
     */
    public FlowInput createFlowInput() {
        return new FlowInput();
    }

    /**
     * Create an instance of {@link ControlInput }
     * 
     */
    public ControlInput createControlInput() {
        return new ControlInput();
    }

    /**
     * Create an instance of {@link StockInput }
     * 
     */
    public StockInput createStockInput() {
        return new StockInput();
    }

    /**
     * Create an instance of {@link Step }
     * 
     */
    public Step createStep() {
        return new Step();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InputSet }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://24.19.117.165/xml/input", name = "inputs")
    public JAXBElement<InputSet> createInputs(InputSet value) {
        return new JAXBElement<InputSet>(_Inputs_QNAME, InputSet.class, null, value);
    }

}
