//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.07 at 10:32:12 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://24.19.117.165/xml/input", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package xmlobjects;
