//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.07 at 10:32:12 PM PDT 
//


package xmlobjects;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for step complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="step">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="stock" type="{http://24.19.117.165/xml/input}stockInput" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="flow" type="{http://24.19.117.165/xml/input}flowInput" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="control" type="{http://24.19.117.165/xml/input}controlInput" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="stepValue" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="relative" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "step", propOrder = {
    "stockOrFlowOrControl"
})
public class Step {

    @XmlElements({
        @XmlElement(name = "stock", type = StockInput.class),
        @XmlElement(name = "flow", type = FlowInput.class),
        @XmlElement(name = "control", type = ControlInput.class)
    })
    protected List<Object> stockOrFlowOrControl;
    @XmlAttribute(name = "stepValue", required = true)
    protected BigInteger stepValue;
    @XmlAttribute(name = "relative", required = true)
    protected boolean relative;

    /**
     * Gets the value of the stockOrFlowOrControl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stockOrFlowOrControl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStockOrFlowOrControl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StockInput }
     * {@link FlowInput }
     * {@link ControlInput }
     * 
     * 
     */
    public List<Object> getStockOrFlowOrControl() {
        if (stockOrFlowOrControl == null) {
            stockOrFlowOrControl = new ArrayList<Object>();
        }
        return this.stockOrFlowOrControl;
    }

    /**
     * Gets the value of the stepValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStepValue() {
        return stepValue;
    }

    /**
     * Sets the value of the stepValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStepValue(BigInteger value) {
        this.stepValue = value;
    }

    /**
     * Gets the value of the relative property.
     * 
     */
    public boolean isRelative() {
        return relative;
    }

    /**
     * Sets the value of the relative property.
     * 
     */
    public void setRelative(boolean value) {
        this.relative = value;
    }

}
